### ISSUE TITLE
Which version of ldm did you use in the project?

### ISSUE THREAD

**Issue by Exusial** [snuvclab/chupa#1]
Thank you for your exciting work! I'm currently trying to run the inference code but find no instructions on how to install the ldm module. I tried the repo of CompVis but it doesn't work. Could you give some hints? Thanks again!

**Comment by bjkim95** [comment]
Hi, thank you for interest in our work!

As far as I understood, you are in trouble importing the ldm module, right?

Our code already includes ldm related code under `src` folder.
`pip install -e .`  will enable the import of ldm module under `src` folder.
In fact, this installation is included in environment.yaml. If you successfully ran 'conda env create -f environment.yaml`, there should be no problem for importing ldm module.

If I missed the point or you have other questions, please let me know.

**Comment by bjkim95** [comment]
Sorry for the late response.

You may see src/ldm/models/diffusion/image_editor.py. (If you don't, please clone our repository again)
The error you mentioned is the code cannot see that file.
`python setup.py develop` or `pip install -e .' makes the codes under `src/` folder as libraries(ldm, normal_nds, ..) 
and you can import them anywhere.

If you just want to 'run' it, please try relative import.

Thanks.
