### ISSUE TITLE
difference between rp_ben_posed_001, rp_ben_posed_003

### ISSUE THREAD

**Issue by Zheng-Yuzhou** [snuvclab/chupa#10]
Hello, I successfully ran the code of chupa on my computer and generated several folders in resultsrenderpeople: rp_ben_posed_001, rp_ben_posed_003...what is the difference between the models contained in these folders: 001, 003, 007, 008, I found a big difference in these model files

**Comment by bjkim95** [comment]
Hi, thank you for your interest in our work.
rp_ben_posed_001, 003.. are the names of scans in the renderpeople dataset.
And each scan has different poses.
The generated model follows the pose of the specified scan.
For example, you can see the original scan of [rp_ben_posed_001](https://renderpeople.com/3d-people/ben-posed-001/).

If you have further questions, please let me know.

**Comment by Zheng-Yuzhou** [comment]
Thanks to your reply, I understand the generative model for different characters and different poses, and I am very interested in your work
