### ISSUE TITLE
About orthographic projection

### ISSUE THREAD

**Issue by boqian-li** [snuvclab/chupa#12]
Hi, thanks for your great work!  I saw you used orthographic projection normal map for training. I want to know if it is necessary to use orthographic projection instead of perspective projection or if it has a big influence on the result.

**Comment by bjkim95** [comment]
Hi, thank you for your interest in our work!

You don't have to use orthographic projection.
I haven't tested the perspective projection, but I believe it may not make a big difference.
I followed the rendering convention of previous work like PIFu, ICON, etc.
