### ISSUE TITLE
Some bugs when running gradio

### ISSUE THREAD

**Issue by azuxmioy** [snuvclab/chupa#3]
1. Should rename `scripts/gradio.py` as `scripts/gradio_test.py`

Otherwise, this [line](https://github.com/snuvclab/chupa/blob/main/scripts/chupa.py#L33C1-L33C1) will not work. Also, there will be some importing issues if using the name `gradio.py`

2. The order of the input arguments [here](https://github.com/snuvclab/chupa/blob/main/scripts/chupa.py#L228) is wrong.
It should be 
```
        return self.forward(None, input_image, None, seed, steps, cfg_scale, image_cfg_scale,
                    use_resample, resample_T, n_resample, 
                    use_closeup, resample_T_face, n_resample_face,
                    use_text, prompt, negative_prompt )
```
Otherwise, it will cause some problems when using text prompts and resampling

**Comment by bjkim95** [comment]
Hi, 

thanks for letting me know. I'll update the code based on your comment.
