### ISSUE TITLE
Missing checkpoints

### ISSUE THREAD

**Issue by SangHunHan92** [snuvclab/chupa#6]
Thanks for great work !

I run [code](https://github.com/snuvclab/chupa#pretrained-model) for download checkpoints, but I can't find following file from here :
`checkpoints/normal_ldm/dualbody-text-rpth-3dim/config.yaml`

Can I download checkpoints for inference using text prompts?

**Comment by bjkim95** [comment]
Hi, thank you for your interest in our work!

I've just checked whether the current checkpoint command is valid and it looks okay.
Would you check whether any error occurs during the download process?

**Comment by bjkim95** [comment]
You should check whether the checkpoint file and config file exists under `dualbody-text-rp-3dim` folder.
If you ran the download command without errors, both checkpoint and config file should exist.
Please rerun the download command and check whether the error occurs or not.
I checked today that the download command gives the checkpoint and config file.
![image](https://github.com/snuvclab/chupa/assets/66873933/85fb6332-819d-4557-a40f-7f60b2c5630a)

**Comment by SangHunHan92** [comment]
Oh! There seems to be some misunderstanding.
This appears to require a folder called `dualbody-text-rpth-3dim`, not `dualbody-text-rp-3dim`.

Or do I need to change the `diffusion` parameter in configs/text.yaml for that code to run?
So, the text model that learned RenderPeople&THuman2.0 hasn't been released yet?

**Comment by bjkim95** [comment]
Ah, now I understand. Sorry for the inconvenience.
[checkpoints_231207.zip](https://drive.google.com/file/d/1N1n9MWdnrNANFZvwaCRx7oyX8LPnIteu/view?usp=sharing)
Would you test this checkpoint file? This includes the text checkpoint trained with renderpeople + thuman2.0.

I'll update the readme file in a few days.
