### ISSUE TITLE
about text-guided normal map generation

### ISSUE THREAD

**Issue by PGogo** [snuvclab/chupa#8]
I am interested in your work, and it is a really nice one.
I test chupa with text-guidence, but I found out the results are not as what I describe.
Here are two samples guided by the prompt "girl,long hair,swimsuits". They dont look like wearing the swimsuits.
![000](https://github.com/snuvclab/chupa/assets/41355904/0a0256c0-9342-47c1-820b-2d681433e8fe)
![000](https://github.com/snuvclab/chupa/assets/41355904/9b10be07-28bf-44a0-ae8d-b69080f1fac6)
Can you give me some suggestions?
Thanks !!

**Comment by bjkim95** [comment]
Thank you for your interest in our work.
Since our text model was not trained with large-scale data, it cannot handle all types of prompts.
(3D scans are not abundant compared to 2D data)
It's one of our limitations honestly speaking.

Thanks
