### ISSUE TITLE
Is autoencoder trained from scratch or finetuned from vq-f4-c3 weight?

### ISSUE THREAD

**Issue by sungmin9939** [snuvclab/chupa#9]
I downloaded pretrained weight from google drive and ommer lab.

there are two files under autoencoder/vq-f4-c4: config.yaml and checkpoint file
It seems that the checkpoint file is for VQModel which is trained(or finetuned) with normal map images.

and there is also a config file that seems to be used for VQmodel training.
Since checkpoint path is not written in the config file, it looks like the model was trained from scratch. Am I correct?
Didn't you use the weight file in vq-f4-c3?

**Comment by bjkim95** [comment]
Hi, 

The checkpoint for vq-f4-c4 is trained with normal maps from scratch.
The checkpoint for vq-f4-c3 is the one from Ommer Labs, not trained by ourselves.

If you have further questions, please let me know.

Thanks

**Comment by sungmin9939** [comment]
I totally understand with your answer! thanks!
